# connfi server
server.port=8081
spring.application.name=geolocalizacion

# conexion postgresSQL docker
spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvos_mascotas
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion jpa y postgis
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones de locationiq
locationiq.api.key=pk.061193d3fb86661fa69fa8190957131b
locationiq.api.url=https://us1.locationiq.com/v1/search.php